import type { GuidePage } from '../types'
import { page, paragraphs } from '../helpers'

export const historyOfKabah: GuidePage = page({
  slug: 'history/history-of-kabah',
  title: "History Of Ka'bah",
  section: 'history',
  heroImage: '/images/kiswah-detail.webp',
  sourceUrl: '',
  blocks: paragraphs(
    "Prophet Ibraaheem (peace be upon him) was commanded by Allah to leave his second wife, Haajar, and their newly born son, Ismaa'eel, alone in the un-inhabited and barren valley of Bakkah (also known as Makkah). However, he used to return to visit them periodically. After Prophet Ibraaheem (peace be upon him) left them, their supplies ran out and Haajar went in search of water. She left the baby, Ismaa'eel (peace be upon him), in the valley and ran between the hills of Safaa and Marwah trying to see if there were any oasis nearby or if any travelers were in the area. As Allah willed it, a spring started bubbling forth from the sand near the feet of the baby Ismaa'eel (peace be upon him). This spring became known as Zamzam and eventually became a well. During one of his visits, Prophet Ibraaheem (peace be upon him) and his son Ismaa'eel (peace be upon him) were commanded by Allah to lay the foundations of the first house built expressly for the worship of Allah, which became known as the Ka'bah. In subsequent visits they completed the building of the Ka'bah. Allah described the Ka'bah and its building in the Qur'an as follows:",
    '"The first house (of worship) founded for mankind was that at Bakkah; a blessing and guidance for all people." (3:96)\n"And remember when Ibraaheem (peace be upon him) and Ismaa\'eel (peace be upon him) laid the foundation of the House (of worship)." (2:127)',
    "In order to mark a specific starting point for circling the Ka'bah, Prophet Ibraaheem (peace be upon him) placed a special stone in its eastern corner. This stone, according to the Prophet Muhammad's (peace be upon him) explanation, was originally shining white in color when it was brought down from Paradise; however, due to the sins of man, it changed to its present color of dull black — hence its name, Al-Hajar al-Aswad (the Black Stone).",
    'During the building of the Ka\'bah, Prophet Ibraaheem (peace be upon him) stood on a large stone block to complete the upper part of its wall. He used to move the block around the Ka\'bah as he built it, and on completion of the building it was left outside the Ka\'bah near the eastern wall, becoming known in later years as Maqaam Ibraaheem (the standing place of Ibraaheem, peace be upon him).',
    "In Ibraaheem's (peace be upon him) time, the Ka'bah reached a height of 4.5 meters. It was rectangular in shape: 16 meters from the eastern side, 15.5 meters from the west, 10 meters from the south, and 11 meters from the north. On the northern angle of the Ka'bah he built a curved (semi-circular) shaft to serve as a yard for Ismaa'eel's sheep (peace be upon him). Ibraaheem (peace be upon him) built two doors at ground level and did not put a roof on it. He would come to Makkah once per year to perform the rites of Hajj with his family until he died. His son Ismaa'eel (peace be upon him), who had by then married a woman from the tribe of Jurham, continued the tradition of Hajj and looked after the Ka'bah until he died.",
    "The Ka'bah then fell into the possession of the Jurhum tribe, which had settled in the valley of Makkah. It remained in their hands for a thousand years until it became the property of the Khuzaa'ah tribe, who in turn held it for another three hundred years. Since the Ka'bah was at the bottom of the valley surrounded by bare hills, it was constantly exposed to floods. On one occasion it was completely destroyed but was rebuilt by Qusay ibn Kilaab in its original form, except that he added a roof to protect it from the elements.",
    "Idolatry was introduced into Arabia by 'Amr ibn Luhay, who brought the idol Hubal from Mesopotamia (Iraq) and placed it inside the Ka'bah. Later, a large wooden dove was also placed inside the Ka'bah, and the inside walls were covered with paintings of the Prophets, including a picture of Eesa (peace be upon him) and his mother. Eventually, over 360 idols were placed around the Ka'bah, along with altars for slaughtering animals to the idols. During the annual fairs of 'Ukaadh, poetry competitions were held, and the seven most outstanding odes were etched in gold and hung inside the Ka'bah — these poems were called the Mu'allaqaat (\"the hanging things\"). The tribe of Qusay was the first to build dwelling-houses around the Ka'bah. Their successors were the Quraish. Soon after they came into possession of the Ka'bah, a fire from a woman incensing the building is said to have caught and laid part of it to waste. Since successive floods had again weakened its structure, the Quraish took it upon themselves to rebuild the Ka'bah. In approximately 600 CE, the Quraish gathered funds untouched by Ribaa (interest) or illegal means in order to rebuild it. A Byzantine ship had been thrown ashore at Jeddah, and the Makkans bought its wood and used it for the new building. The Ka'bah was then built in alternating layers of stone and wood.",
    "When the work reached the placement of the Black Stone, a quarrel broke out among the tribes — each wished the honor of raising it into place. They agreed that the first man to enter the Haram (the area immediately around the Ka'bah) should decide for them. Muhammad (peace be upon him) happened to be first to enter, and was appointed arbitrator. He told them to place the stone on a cloth, with a representative of each tribe holding a portion of the cloth, and together they lifted it into place. Prophet Muhammad (peace be upon him) then fixed it in position with his own hand. In the course of this rebuilding, the height of the Ka'bah was doubled, its western door was sealed off, and its eastern door was placed above ground level to prevent common people from entering. However, due to a shortage of lawfully-gathered funds, they reduced about six Azhru (arm's length) and a hand-span (roughly 3 meters) from the Hijr side of the house. They also increased its height to 9 meters and added a roof, which it had not had before. The shortened section became known as Hijr Ismaa'eel.",
    "At the conquest of Makkah in 8 AH (630 CE), Prophet Muhammad (peace be upon him) left the Ka'bah's structure unaltered but destroyed all the idols in and around it and removed the paintings from its inner walls. He said only the very recent conversion of the Makkans prevented him from returning it fully to the form of Ibraaheem's (peace be upon him) time. This intention was realized in 683 CE by 'Abdullaah Ibn Az-Zubayr, who rose in rebellion against Caliph Yazeed. During the siege that followed, catapults were used against Makkah, smashing the Ka'bah and splitting the Black Stone into three pieces. After the siege was lifted in 684 CE, Ibn Az-Zubayr rebuilt the Ka'bah according to its original form, based on a tradition from his aunt Aishah (may Allah be pleased with her), who reported the Prophet (peace be upon him) once told her he would have rebuilt the House to include the portion the Quraish had cut away, with a door on the east and another on the west, had the people not been so recently converted to Islam. [Al-Bukhari, Sahih, vol. 2, pp. 574; Muslim, Sahih, vol. 2, pp. 969]",
    "In 74 AH (693 CE), Al-Hajjaaj Ibn Yoosuf conquered Makkah and, in agreement with Caliph 'Abdul-Malik Bin Marwaan, rebuilt the Ka'bah according to the earlier Quraishy form — again separating the Hijr and walling up the west door, reducing the structure back toward the Hijr, though without changing its height. This form has survived to the present day.",
    "Seasonal flooding continued to threaten the building; in 1611 CE a huge copper band was placed around its walls. In 1630 CE, Makkah was struck by a major flood and the north wall of the Ka'bah collapsed. Ottoman Sultan Muraad Khaan ordered it demolished and rebuilt using the original stones, maintaining the Quraishy design — the construction that remains to this day.",
    'In 1957, during the reign of King Saud, a new wooden roof was installed along with several minor renovations. In 1417 AH, King Fahd Bin Abdul Aziz (may Allah have mercy on him) ordered comprehensive renovations: the foundations were strengthened, the loops and shadharwaan were renovated, the outside walls were brushed up, gaps between construction stones were blocked, and the dual roofs of the Ka\'bah were replaced with new ones.',
  ),
})
