import type { GuidePage } from '../types'
import { page, paragraphs } from '../helpers'

/** Content from scripts/output/alhussam-guide-scrape.json — history_kabah.php */
export const historyOfKabah: GuidePage = page({
  slug: 'history-of-kabah',
  title: "History Of Ka'bah",
  section: 'history',
  subtitle: 'The House of Allah — from Ibraaheem (peace be upon him) to the present day',
  heroImage: '/images/kiswah-detail.webp',
  sourceUrl: 'https://www.alhussam.in/history_kabah.php',
  blocks: paragraphs(
    "During the building of the Ka'bah Prophet Ibraaheem (peace be upon him) stood on a large stone block in order to complete the upper part of its wall. He used to move the block around the Ka'bah as he built it and on completion of the building, it was left outside the Ka'bah near the eastern wall and became known in later years as Maqaam Ibraaheem (the standing place of Ibraahim (peace be upon him)).",
    "In Ibraaheem's (peace be upon him) time, the Ka'bah reached a height of 4.5 meters. It was rectangular in shape 16 meters from the eastern part, 15.5 meters from the west, 10 meters from the south and 11 meters from the north. On the northern angle of the ka'bah he built a curved (semi-circular) shaft to serve as a yard for Ismaa'eel's sheep (peace be upon him). Ibraaheem (peace be upon him) built in it two doors at ground level and did not put a roof on it. He would come to Makkah once per year to perform the rites of Hajj with his family until he died. His son Ismaa'eel (peace be upon him) who had by then married a woman from the tribe of Jurham, continued the tradition of Hajj and looked after the Ka'bah until he died.",
    "The Ka'bah then fell into the possession of the Jurhum tribe which had settled in the valley of Makkah. It remained in their hands for a thousand years until it became the property of the Khuzaa'ah tribe who in turn held it for another three hundred years. Since the Ka'bah was at the bottom of the valley surrounded by bare hills, it was constantly exposed to floods. On one occasion it was completely destroyed, but was rebuilt by Qusay ibn Kilaab in its original form except that he added a roof to it to protect it from the elements.",
    "Idolatry was introduced into Arabia by 'Amr ibn Luhay,who brought the idol, Hubal from Mesopotamia (Iraq) and placed it inside the Ka'bah. Later a large wooden dove was also placed inside the Ka'bah and the inside walls of Ka'bah were also covered with paintings of the Prophets including a picture of Eessa (A.S) and his mother. Eventually over 360 idols ware replaced around Ka'bah as well as altars for slaughtering animals to the idols. During the annual fairs of 'Ukaadh, poetry competitions were held and the seven most outstanding odes were etched in gold and hung inside the Ka'bah. These poems were called the Mu'allaqaat, literally the hanging things, and the best poet win the honor was Imral-Qays (died 540CE). The tribe of Qusey was the first to built dwelling-houses around the Ka'bah. The successors of the Qusey tribe were the Quraish. Soon after they came into possession of the Ka'bah, the fire of a woman incensing the Ka'bah is said to have caught the building and laid part of it to waste. Since successive floods had again weakened its structure, the Quraish took it upon themselves to rebuilt the Ka'bah. In approximately 600 CE the Quraish gathered funds which had not been touched by Ribaa (interest) or illegal means in order to rebuild the Ka'bah. It happened that a Byzantine ship was thrown ashore at Jeddah and the Makkans bought its wood and used it for the new building. The Ka'bah was then built at alternate layers of stone and wood. When the work reached the place of the Black Stone, a quarrel broke out among the tribes.",
    "Each tribe wished to have the honor of raising the Black Stone into its place. Eventually they agreed that the first man to enter the Haram (the area immediately around the Ka'bah) should decide for them. Muhammad (peace be upon him) happened to be the first to enter and he was appointed arbitrator. He then told them to place the stone upon a cloth and a representative of each tribe was to take hold of a portion of the cloth and together they would all lift it into its place. The dispute was thus ended and when the stone had reached its proper place, Prophet Muhammad (peace be upon him) fixed it in its position with his own hand. In the course of the building of the Ka'bah its height was doubled, its western door sealed off and its eastern door was placed above ground level to prevent the common people from entering it. However, due to the shortage of funds untouched by Ribaa (interest) or illegal means, as a result they could not gather enough lawful money to complete the building. Therefore, they reduced about six Azhru (arms length) and a span of the hands length (3m) from the hijr side of the house. They also made some changes in it by increasing its height (9m) and making a roof for it since it was not roofed before. The length of the Ka'bah was shortened leaving it in the now familiar cubic form and semicircular wall was built behind the main structure to indicate the excluded portion and the encompassed area become known as Hijr Ismaa'eel. At the conquest of Ka'bah in 8 A.H. (630 CE).",
    "Prophet Muhammad (peace be upon him) left the Ka'bah as a building unaltered. However, he destroyed all of the idols in and around the Ka'bah and the paintings were removed from the inner walls of the building. He also said that only the very recent conversion of the Makkans prevented him from returning it to the form of Ibraaheem's (peace be upon him) time. These intentions of Prophet Muhammad (peace be upon him) were bought to realization in 683 CE by 'Abdullaah Ibn Az-Zubayr. 'Abdullaah Ibn Az-Zubayr and his followers rose in rebellion against the Caliph Yazeed, who had been forced upon the muslims by his father Capliph Mu'aawiyah. They were soon besieged in Makkah by Caliph Yazeed's army under the command of Al-Husayn Ibn Numayr. During the siege, catapults of Yazeed's army were erected on the hills around Makkah and huge boulders were hurled on the town and the sanctuary resulting in the smashing of the Ka'bah and the splitting of the Black Stone into three pieces. After siege was lifted in 684 , Ibn Az-Zubayr ordered that Ka'bah be rebuilt according to the original form. He wanted to do this as a way of hoping for good omen or good augury in what the Messenger of Allah (may the blessing and peace of Allah be on him ) had wished to do. He had heard from his maternal aunt Aishah (may Allah be pleased with her) that the Prophet (may the blessing and peace of Allah be on him) once said to her:",
    "'Dear Aishah! had your people not still fresh in Islam I would have ordered the House to be demolished so that I will rebuild it, adding to it the portion that was reduced from it, affixing it with the earth and making a door for it from the east and another from the west so that it will meet up with the original foundation of Ibrahim' [Al-Buhaari in his Sahih,vol.2, pp.574 and Muslim in his Sahih vol.2,pp. 969]. Abdullah Bin Az-Zubair included the portion which the Quraish had cut away from the Ka'bah which is (6 Zhiraa and one shibr ) 3 meters and a span of the hands length. He also made for it two doors that were affixed to the ground, one from the east and the other from the western part. He further increased its height to 27 Zhiraa (13.5m). These alteration lasted only a shortperiod.",
    "In (74 AH/693 CE), Al-Hajjaaj Ibn Yoosuf conquered Makkah and killed 'Abdullah Ibn Az-Zubayr. In agreement with the Caliph 'Abdul-Malik Bin Marwaan, he rebuilt the Ka'bah according to the Quraishy form. He again separated the Hijr from Ka'bah and walled up the west door. He demolished the northern wall and reduced about (6 Zhiraa and a shibr) 3 meters and a span of the hands length from it towards the area of the Hijr. However he did not make any changes to its height.",
    'Some historical narrations state then when Abdul Mailk Bin Marwaan knew that Ibn Az-Zubair had depended on the tradition narrated by Aishah (may allah be pleased with her) in his reconstruction he regretted over having permitted Al-Hajjaaj to execute the amendments he did.',
    "The building, in keeping with the wishes of the Umayyads, thus practically received its pre-Islamic form again and this form has survived to the prevent day. However, the Caliph Haroon Ar-Rasheed (or as others write, his father Al-Mahdi or his grandfather, Al-Mansour) intended to again change what had been altered by al-Hajjaaj and reduce the Ka'bah to the old form in which it had been left by 'Abdullaah ibn az-Zubayr but was dissuaded from meddling with it in order to prevent so holy a place from becoming the sport of princes, from being newly modeled after everyone's fancy and form losing the reverence which is justly paid it. Thus, the piety of the populace has always resisted any considerable innovations to the Ka'bah's structure. Only to an unimportant degree have the authorities now and then made improvements. The Ka'bah remained as it was until the beginning of the seventeenth century CE.",
    "Seasonal flooding continued to present a danger to the building and in 1611 a huge copper band was placed around its walls to prevent its eminent collapse. However, in (1040 AH/1630 AD) Makkah was struck by a major flood and the north wall of the Ka'bah finally collapsed. Ottoman Sultaan Muraad Khaan then ordered that the Ka'bah be demolished and rebuilt using the original stones and maintaining the Quraishy design. This construction is the one that remains till this day.",
    "In 1957, during the reign of King Saud, a new wooden roof was put in place and several other minor renovations were introduced. King A'ad Tubba' of the South Yemeni tribe of Himyar was the first to place a cloth covering (called Kiswah) on the Ka'bah..Through time and age the caliphs, sultans and governors have been hastening to rebuilt and amend any faulty area in the ka bah. In the year (1417AH) the custodian of the two sacred mosques King Fahd Bin Abdul Aziz (may Allah have mercy on him ) gave orders to make some comprehensive renovations in the Holy Ka'bah. Hence the foundation were strengthened; the loops and the shadharwaan were renovated. The outside walls were brushed up. The gaps between the construction stones were blocked and the dual roofs of the ka bah were replaced with new ones.",
  ),
})
