import type { GuidePage } from '../types'
import { heading, page, paragraphs } from '../helpers'

export const storyOfZamzam: GuidePage = page({
  slug: 'history/story-of-zam-zam',
  title: 'Story of Zam Zam',
  section: 'history',
  heroImage: '/images/safa-marwa.webp',
  sourceUrl: '',
  blocks: [
    ...paragraphs(
      "Prophet Ibraaheem (peace be upon him) was commanded by Allah to leave his second wife, Haajar, and their infant son, Ismaa'eel, alone in the un-inhabited and barren valley of Bakkah (also known as Makkah). After Prophet Ibraaheem (peace be upon him) left them, their supplies ran out and Haajar went in search of water. She left the baby, Ismaa'eel (peace be upon him), in the valley and she ran seven times back and forth in the scorching heat between the two hills of Safa and Marwa to look for water for Ismaa'eel (peace be upon him), who was dying of thirst, and also trying to see if there were any oasis nearby or if any travelers were in the area for help. Allah, in His mercy, sent the Angel Gabriel, who scraped the ground, a spring started bubbling forth from the sand near the feet of the baby Ismaa'eel (peace be upon him). This spring became known as Zamzam and fearing that it might run out of water, Haajar enclosed it in sand and stones. The name Zamzam originates from the phrase Zomë Zomë, meaning 'stop flowing', a command repeated by Haajar during her attempt to contain the spring water. The area around the spring, which was later converted to a well, became a resting place for caravans, and eventually grew into the trading city of Makkah, birthplace of the Prophet Muhammad (peace be upon him).",
      "Prophet Ibraaheem (peace be upon him) later returned to rebuild Ka'bah, the first Bait-ul-Allah (House of Allah). The Ka'bah now stands in the center of the Holy Mosque, also called Al-Haram. The Zamzam well is located within the Holy Mosque at about 20 m east of the Ka'bah.",
      'Abdullah Bin Abbas (May Allah be pleased with both of them) reported that the Messenger of Allah (May the blessings and peace of Allah be upon him) said: "The best water on the surface of the earth is the water of ZamZam; it nourishes as food and cures from diseases." [At-Tabaraani, Al-Mu\'jam Al-Kabir, vol. 11, pp. 98]',
      'Jabir (May Allah be pleased with him) reported that the Messenger of Allah (peace be upon him) said: "The water of Zamzam will be for that for which it is drunk." [Ibn Maajah vol. 2, pp. 1018; Ahmad vol. 3, pp. 357]',
      'It is the blessed water by which the heart of the Prophet (peace be upon him) was washed. The Holy Prophet (peace be upon him) also blessed it with his spittle. Since then the water of ZamZam had remained for the inhabitants of Makkah and its visitors to drink from.',
      "All able-bodied Muslims with sufficient financial means are obliged to make the pilgrimage to Makkah, known as the Hajj, at least once in a lifetime. During the Hajj, pilgrims perform a number of rituals in Al-Haram and outside Makkah at Muna, Arafat, and Muzdalifa. One of the rituals, known as Umrah, includes Tawaf (seven times circling) of Ka'bah and Sai between the hills of Safa and Marwa, which re-enacts Haajar's search for water. Hajj is performed on specific dates during Dhu Al-Hijja, the last month of the Islamic year, while Umrah is optional and can be performed at any time of the year. Millions of Muslims visit Makkah to perform Umrah and Hajj throughout the year; the peak season being the month of Ramadan and Dhu al-Hijja. Visitors cherish drinking Zamzam water during their visit and carry it back home.",
    ),
    heading(2, 'Structure and Hydrogeology of the Well'),
    ...paragraphs(
      'Zamzam Well is hand-dug and is about 30.5 m deep, with an internal diameter ranging from 1.08 to 2.66 m. Hydrogeologically, the well lies within Wadi Ibraaheem, which runs through the Holy City of Makkah, and taps groundwater from the wadi alluvium and, to a much lesser extent, the underlying fresh bedrock. The well is now housed in a basement room, protected by glass panels that allow a clear view of the well.',
      'Electric pumps are used to draw water from the well, replacing the ropes and buckets of olden days. No visitor is allowed to enter the Zamzam Well room and its surroundings. Outside this room, there was a service area where cold Zamzam water fountains and dispensing containers were provided for drinking purposes. Recently, the Al-Haram Tawaf area has been extended to cover the entrance to this area and it is no longer accessible to pilgrims. Instead, cold Zamzam water fountains and dispensing containers are now placed at the periphery of the Tawaf area and within the Grand Mosque, and open piazzas (Al-Sahat) surrounding the Al-Haram building. Moreover, a bottling plant and public distribution point (Sabeel) have been established at Kudai, south of Al-Haram, for visitors who want to carry Zamzam home.',
      'The upper 13.5 m of the well is excavated in the sandy alluvium of Wadi Ibraaheem, and the lower 17.0 m in the underlying diorite bedrock. In between lies a 0.5 m thick, highly permeable weathered rock layer. Most of the alluvial section of the well is lined with stone masonry except for the uppermost 1 m, which has a reinforced concrete collar. The weathered-rock section is lined with stone, and it is this section that provides the main water entry into the well.',
    ),
  ],
})
